### ISSUE TITLE
Table view is missing

### ISSUE THREAD

**Issue by wetzler** [keen/explorer#112]
As a user, I want to be able to easily copy & paste the results of my aggregations for use in excel, google sheets, keynote, etc.

I used to use the "table" visualization type for this, but recently I noticed it is missing from the explorer.

**Comment by dustinlarimer** [comment]
@wetzler seems to be working for me.. perhaps an AdBlocker?

<img width="786" alt="screen shot 2016-02-01 at 2 43 30 pm" src="https://cloud.githubusercontent.com/assets/180438/12733893/37e6a10c-c8f2-11e5-88cd-e404f8666dab.png">

**Comment by wetzler** [comment]
Ah, I should have clarified that I'm looking for a table on time series metrics. 
Like "count pageviews this_7_days daily".

Steps to repro:
1. Create a count with an interval. 
2. Look for table display option.

**Comment by wetzler** [comment]
Per @maggiejan, another customer asked about "Table visualization when using intervals". Looking forward to getting this shipped! :dancer:
