### ISSUE TITLE
Grammar: "There was a problem: Choose an Target Property."

### ISSUE THREAD

**Issue by wetzler** [keen/explorer#115]
it should say "a" instead of "an"

![screen shot 2016-02-01 at 9 52 14 pm](https://cloud.githubusercontent.com/assets/1840448/12741088/48357a1a-c92e-11e5-9d69-9aba42652fb7.png)

**Comment by aroc** [comment]
Fixed by https://github.com/keen/explorer/commit/43d56f5baa33d2887e7b175990e34245393e1903
