### ISSUE TITLE
Can't update saved query

### ISSUE THREAD

**Issue by wetzler** [keen/explorer#118]
As a user of Keen's explorer, I want to be able to open a saved query, modify it, and then save my changes.

When updating & renaming my saved query, I got the following error:

"Problem updating: The specified value is invalid for the specified property for this cached query. Property: target_property. Value: None"

The error doesn't really make sense since the query runs fine and I have a target property specified.

![screen shot 2016-02-02 at 1 54 35 pm](https://cloud.githubusercontent.com/assets/1840448/12765712/d1151508-c9b4-11e5-8ce1-83baf7273125.png)

I don't have time to confirm the repro on another saved query, but the steps I took were something like this:
1. Open a saved query.
2. Modify the timeframe & add an interval.
3. Change the query type from count to count_unique & add a target property.
4. Run the query and results look good.
5. Rename the query.
6. Click update. 
7. Get the error "Problem updating: The specified value is invalid for the specified property for this cached query. Property: target_property. Value: None"

**Comment by menismu** [comment]
I can reproduce the bug following exactly the steps reported. I´ve investigated a bit the cause of the problem and when the update button is clicked to update the query the service below is consumed:

https://api.keen.io/3.0/projects/PROJECT_ID/queries/saved/saved-query?api_key=API_KEY
Request Method: PUT
Content-Type: application/json

A copy of the payload in the request:

{
    "query_name":"saved-query-m",
    "refresh_rate":0,
    "metadata":{
        "display_name":"Saved query m",
        "visualization":{
            "chart_type":"metric"
        }
    },
    "query":{
        "event_collection":"purchase",
        "analysis_type":"count_unique",
        "target_property":"payment_type",
        "timeframe":{
            "start":"2016-08-19T00:00:00.000+00:00",
            "end":"2016-08-21T00:00:00.000+00:00"
        }
    }
}

An the error message received:

{"message": "The specified value is invalid for the specified property for this cached query. Property: target_property. Value: None", "error_code": "InvalidPropertyValueForCachedQuery"}

I guess the issue could be in the payload, although target_property has in the payload the value "payment_type" does it in the right place? Or it could be a problem in the service updating the query based in the request payload. I´ve had a look to the API documentation in https://keen.io/docs/api/#updating-saved-queries but I haven´t get a clue.

I hope this helps a bit to identify the bug and get it fixed.

**Comment by aroc** [comment]
@menismu The bug is an intermittent issue with our API, not one in Explorer.

**Comment by menismu** [comment]
Ok, one questions, shall the Explorer reacts when this bug happens and show a message to the user?

**Comment by aroc** [comment]
@menismu Yes it should. We're working on it on our end though, so I'd say you can ignore this issue for the time being.
