### ISSUE TITLE
Issue with renaming a saved query

### ISSUE THREAD

**Issue by wetzler** [keen/explorer#119]
I tried to rename my query, but when I did the query name flipped back to the old name, and no visualization was shown.

I think my steps were like this:

1. Load a saved count query
2. Modify the timeframe from "previous month" to an absolute timeframe with a monthly interval. 
3. Run the query and it looks good.
4. Rename the query from "New paying customers this month" to "New paying customers monthly"
5. Press update.
6. Notice that the name reverted back to "New paying customers this month".
7. Notice that the graph is now missing when I run the query, and there is an error.
8. Notice that the interval changed to "minutely".
9. Notice that when I run the old saved query URL, "https://keen.io/project/PROJECT/explorer?saved_query=New-Paying-Customers-This-Month", it says "could not be found".

Sorry this isn't a very good bug report. It will take some time to nail down exactly what the problem is.

![screen shot 2016-02-02 at 2 05 19 pm](https://cloud.githubusercontent.com/assets/1840448/12765990/1b8e702e-c9b6-11e5-9e78-c730f0e6e501.png)

**Comment by aroc** [comment]
This is because of this problem here: https://github.com/keen/explorer/issues/68

Closing in favor of the other issue.
