### ISSUE TITLE
I'd love a switch to get some larger chart sizes

### ISSUE THREAD

**Issue by hsm3** [keen/explorer#12]
The Explorer is super useful.  I'd really like a way to get some graphs in larger sizes, for sharing in reports and making it easier to decipher crowded charts.

**Comment by dustinlarimer** [comment]
@hsm3 that's a cool idea.. would you just screenshot the charts at a higher resolution? Curious to hear more about these reports, and how we might be able to make that easier as well...

**Comment by hsm3** [comment]
Looks like this got done in the version hosted at keen.io.  (clever to leverage the window resizing gesture)  Thanks much!
