### ISSUE TITLE
Feature request: share reports with non-Keen users

### ISSUE THREAD

**Issue by nemo** [keen/explorer#127]
Hey folks,

Sometimes, we'd like to share reports with our users and/or investors who'd like to get an update on our metrics.

Currently, we take screenshots of the charts and send them over – but it would be lovely to somehow enable the ability to send a unique link that gives the user access to a specific query/saved-query.

This would be relatively simple and possible if the read key was embedded in the query and the explorer used it to perform its query (and the parameters of the query would of course have to passed as well).

**Comment by aroc** [comment]
We have a dashboards in the process of being released right now. Dashboards are likely a much better format for sharing, as you can build it up to contain multiple visualizations backed by saved queries. Making dashboards sharable is definitely something on our minds, although no solid ETA at the moment.

**Comment by aroc** [comment]
Ah, you wanna share ad-hoc queries! That's a bit different and I can see why you'd want it in Explorer in that case. I'll share this with the team.

Also, we definitely are open to PRs. So feel free to send one our way for something like this.

**Comment by Ramblurr** [comment]
Are the dashboards in keen.io's explorer going to come to this open source version?

**Comment by dustinlarimer** [comment]
I'm going to close this issue for now. We have no plans to pursue this in the near future, though if we did pursue it the logic for this would live elsewhere anyhow. Thanks again for the suggestion!
