### ISSUE TITLE
Invalid time JS error in funnel analysis

### ISSUE THREAD

**Issue by garethtdavies** [keen/explorer#128]
When performing a funnel analysis it is not possible to select an actor property due to an Uncaught Error: Invalid time value (see screenshot).

![keen-error](https://cloud.githubusercontent.com/assets/135382/13610617/6565d50c-e513-11e5-9990-e454e79b0b85.png)

**Comment by UberSnip** [comment]
Issue confirmed on my end :+1:

**Comment by dustinlarimer** [comment]
Thanks @garethtdavies @UberSnip! We'll get this patched up in an upcoming release.

**Comment by UberSnip** [comment]
Awesome! Thanks for the update :+1:
