### ISSUE TITLE
Rationale for self-hosting this project

### ISSUE THREAD

**Issue by danmartinez101** [keen/explorer#13]
What scenarios would I want to self-host this explorer? Is it recommended to do that in general, or to use your hosted version?

**Comment by timfalls** [comment]
Hi @danmartinez101 -- a really simple use case for hosting the explorer yourself would be if you wanted to provide the same kind of functionality to your customers (so they could explore the data around their usage of your product) within the native experience of your application. 

You could use the open-source explorer to embed that experience into your web app and (hopefully) delight your users with an awesome data exploration feature, without having to build the software from the ground up!

**Comment by danmartinez101** [comment]
Thanks @timfalls, that makes sense.
