### ISSUE TITLE
The CI setup looks broken

### ISSUE THREAD

**Issue by stof** [keen/explorer#131]
installing deps is failing: https://circleci.com/gh/keen/explorer/327

**Comment by dustinlarimer** [comment]
@stof this appears to be working for us.. still seeing this error?

**Comment by stof** [comment]
I saw this issue when submitting https://github.com/keen/explorer/pull/130 (which triggered the build linked above). I rebased my branch to retrigger a build and it indeed works now. This was probably a temporary issue

**Comment by dustinlarimer** [comment]
@stof awesome, thanks for _circling around_ on this one :)
