### ISSUE TITLE
Optional Steps in Funnel Query are "forgotten" by Saved Queries in the Explorer

### ISSUE THREAD

**Issue by maggiejan** [keen/explorer#135]
"I'm creating a three-step funnel. The second and third step I check the "Optional Step" flag and then save the query, but when it saves it clears the optional flags.  So the next time I run it I have to remember to go in and check those flags again." 

Repeatable steps: 
- step 1: access any saved funnel query
- step 2: check optional for step 3, and then click 'update' to save 
- step 3: immediately the optional box becomes unchecked
- step 4: returning to the saved query reveals the box is still unchecked 

Ideal outcome: Ideally the flag stays after saving a query from the Explorer!

**Comment by aroc** [comment]
Fixed by #136
