### ISSUE TITLE
Error when you modify the property name of an "exists" filter

### ISSUE THREAD

**Issue by wetzler** [keen/explorer#139]
If you use the "property exists" filter and run the query, it works fine. However if you then go back to change the property to filter on, the filter seems to disappear or give an error.

Steps to Repro
1. Run a query like count "action" with a filter for ```<any property> exists true```. It works.
2. Now modify the filter property to any other property and run the query. You get an error ```The specified value is invalid for the given operator. Operator: exists. Value: true```

You can work around it by completely removing your filter and re-creating it.

Today, a Keen Pro customer also reported that it was impacting them.

![screen shot 2016-04-20 at 10 58 06 am](https://cloud.githubusercontent.com/assets/1840448/14684877/cb31c0ea-06e6-11e6-9611-5f788c332ee9.png)

**Comment by wetzler** [comment]
Today, another user reported that this was impacting them.
They were able to workaround it by deleting and re-adding the filter.

**Comment by aroc** [comment]
I've reproduced the bug and am actively working on it today. Thanks for the great report (yet again)! :)
