### ISSUE TITLE
[Feature request] Add ability to clone a saved query

### ISSUE THREAD

**Issue by stof** [keen/explorer#151]
It would be helpful to be able to clone a saved query. The idea would be to populate the explorer with the settings of the saved query, and letting me save it as a different saved query (after doing some changes) instead of updating the existing query.

This is helpful when I have several similar queries to create (just changing one of the filter condition in this case, while keeping all other filters and other things the same)

**Comment by aroc** [comment]
This would be a great feature and we've had it requested several times. Definitely something on our radar! Thanks for sharing your feedback with us :D

**Comment by sfalkoff** [comment]
@stof this feature is live! You should be able to clone saved queries now. 

Thanks again, @menismu, for your contribution implementing this feature in #180.
