### ISSUE TITLE
Filter property name with [ square bracket throws error

### ISSUE THREAD

**Issue by dustinlarimer** [keen/explorer#154]
Filter property name with [ square bracket throws error:
> Uncaught SyntaxError: Invalid regular expression: /request.params.filter[/: Unterminated character class

<img width="743" alt="screen shot 2016-06-01 at 9 36 23 pm" src="https://cloud.githubusercontent.com/assets/180438/15734117/f82f17a2-2840-11e6-8f6c-900532320f92.png">

**Comment by menismu** [comment]
I´m happy to help fixing this bug if it is not yet in the development plan but I would need some indications to see how this component should work, should it accept characters like [ or ]? Is there any other character not allowed?

**Comment by aroc** [comment]
@menismu Yes, we want to allow `[` and `]` characters. The full rules for what's allowed in a Keen property name are here in our docs: https://keen.io/docs/api/#property-name-rules

**Comment by jacklittleton** [comment]
@menismu Keen IO internal resources are beginning to look at this; have you made progress on this, or should we continue? We wouldn't want to have a duplicate effort situation.

**Comment by menismu** [comment]
@jacklittleton I got the fix done but I wanted to also write tests, if you and Keen don't mind to wait few days I will send a pull request before the end of the week with this bug fixed as well as regression test.

**Comment by jacklittleton** [comment]
@menismu Hey, thanks for the PR review! Greatly appreciated!
