### ISSUE TITLE
Funnels get stuck in "Loading" if step 1 is optional

### ISSUE THREAD

**Issue by dustinlarimer** [keen/explorer#157]
Repro:

> Build a funnel with at least 2 steps.
> Run it.
> Go back and mark Step 1 as optional.
> Run it.
> Result: "Loading" appears for a looonnngggg time.... If you look in console you see an error about Step 1.
> Expected result: Step 1 shouldn't have the option to check "Optional" since the API doesn't support if. If it is there and checked, it should be ignored.

**Comment by joannecheng** [comment]
Fixed in PR #1387
