### ISSUE TITLE
Chrome's autocomplete competes with Explorer's

### ISSUE THREAD

**Issue by aroc** [keen/explorer#158]
It seems for some users Chrome's autocomplete is competing with Explorer's own and makes it difficult to select an option.

Discussion around how this works with Chrome here. See final comment at bottom of page (latest comment in the thread).
https://bugs.chromium.org/p/chromium/issues/detail?id=468153

I cannot reproduce this myself.

**Comment by dustinlarimer** [comment]
> In cases where you really want to disable autofill, our suggestion at this point is to utilize the autocomplete attribute to give valid, semantic meaning to your fields. If we encounter an autocomplete attribute that we don't recognize, we won't try and fill it.

> As an example, if you have an address input field in your CRM tool that you don't want Chrome to Autofill, you can give it semantic meaning that makes sense relative to what you're asking for: e.g. `autocomplete="new-user-street-address"`.  If Chrome encounters that, it won't try and autofill the field.

**Comment by aroc** [comment]
^^ I believe that's the solution in case anybody tackles this!
