### ISSUE TITLE
Inserting & running a query on initial render

### ISSUE THREAD

**Issue by jdrydn** [keen/explorer#161]
Howdy,

Is something like this possible:

```js
Keen.ready(function() {
  // Configure a new Keen.js client with your project ID, read key and master key.
  var client = new Keen({
    projectId: "YOUR_PROJECT_ID",
    readKey: "YOUR_PROJECT_READ_KEY",
    masterKey: "YOUR_PROJECT_MASTER_KEY"
  });

  var app = new Keen.Explorer.App({
    client: client,
    targetId: 'explorer',
    query: 'event_collection=sign_up&target_property=member.id&interval=daily&timezone=UTC&timeframe=previous_30_days&filters=%5B%5D'
  });
  app.render();
});
```

Where an initial query could be "inserted" into the rendered Explorer & then executed on complete?

**Comment by aroc** [comment]
Hi @jdrydn, unfortunately that's not supported. The only way to have it Explorer with a query already populated is to have it in the URL. Easiest way is to have that page have the query in the URL already. We've definitely talked about having it be an option to pass into the constructor, so we may add it in the future. Until then, hope this helps!

**Comment by jdrydn** [comment]
In the situation I'm using it in, it's used within an `<iframe/>` tag so I just end up re-rendering the tag with a new query-string attached to it (when a user requests a pre-defined query), which works *really really* well :smile:

Passing it problematically would be awesome, but at least there's a manageable workaround for it :+1:
