### ISSUE TITLE
Cannot use custom intervals on queries

### ISSUE THREAD

**Issue by leonsas** [keen/explorer#162]
The API does support [custom intervals](https://keen.io/docs/api/#custom-intervals), but the Explorer doesn't allow to use that. It only allows for hardcoded intervals.

**Comment by dustinlarimer** [comment]
@leonsas correct, that was an intentional decision to limit the scope of the interface design/build effort earlier on. We may certainly consider this in the future though!

**Comment by adamkasprowicz** [comment]
Good news - this feature is available in keen-explorer@5 (#239)
It will be deployed on the keen.io website in the next 1-2 weeks
