### ISSUE TITLE
Unable to update Saved Query visualization type

### ISSUE THREAD

**Issue by sfalkoff** [keen/explorer#191]
Steps to reproduce:

1. Navigate to the "Browse" tab and click on a saved query. Note the visualization type.

2. Change the visualization type and click "Update" to save the changes.
![screen shot 2016-12-19 at 4 56 00 pm](https://cloud.githubusercontent.com/assets/6183404/21334410/325788c4-c60c-11e6-9e1d-b951259a9974.png)
![screen shot 2016-12-19 at 4 50 17 pm](https://cloud.githubusercontent.com/assets/6183404/21334476/c3c011a0-c60c-11e6-86c2-069391f30c3a.png)

3. Refresh the page. From the "Browse" tab, select the original saved query.
4. **Expected:** The query results display with the new visualization type you just saved.
    **Actual:** The query results are displayed with the original visualization type noted in Step 1.

**Comment by sfalkoff** [comment]
May be related to https://github.com/keen/explorer/issues/118.

**Comment by dustinlarimer** [comment]
This appears to be resolved now- closing 👍
