### ISSUE TITLE
Select field displays incorrect visualization type after saving query

### ISSUE THREAD

**Issue by sfalkoff** [keen/explorer#192]
Steps to reproduce:

1. Run a new count query. Notice that the visualization type is set to "Metric" by default.

![screen shot 2016-12-20 at 11 11 31 am](https://cloud.githubusercontent.com/assets/6183404/21364408/99da4ef2-c6a5-11e6-9df3-9dc61aa98dab.png)

2. Enter a name for your query and save it. Notice that the visualization still displays with the "Metric" chart type (expected), however, the select component shows "Bar" and "Metric" no longer appears in the drop down (not expected). 

![screen shot 2016-12-20 at 11 11 55 am](https://cloud.githubusercontent.com/assets/6183404/21364499/f8371548-c6a5-11e6-9f3d-0943be1d5e8e.png)

I've also seen this issue after saving count_unique queries -- it may be happening with other query analysis types as well.

**Comment by josephwegner** [comment]
Picking this up

**Comment by dustinlarimer** [comment]
@josephwegner @sfalkoff is this resolved?

**Comment by dustinlarimer** [comment]
This appears to be working correctly in prod now- closing 👍
