### ISSUE TITLE
Missing timezone

### ISSUE THREAD

**Issue by SegFaultx64** [keen/explorer#203]
Hi folks,

The explorer is missing the Atlantic Timezone, which is not a huge problem normally since few people live in it. However right now (during DST) -4GMT becomes the time zone in the eastern United States. This means that we basically can't correctly run queries right not :sob:.

**Comment by dustinlarimer** [comment]
@SegFaultx64 thank you for taking time to put #205 together! These timezone records correspond to the list of named timezones supported by the API: https://keen.io/docs/api/#named-timezones, so I'm afraid the update won't have the desired effect. 

I just merged #206 which will set the local timezone appropriately, either selecting a timezone with the corresponding offset, or setting the explicit numerical offset as a backup. I think this should resolve the issue for you. Please let me know if that's not the case!
