### ISSUE TITLE
Can't `import KeenExplorer from `keen-explorer`

### ISSUE THREAD

**Issue by pixelastic** [keen/explorer#228]
Hello all,

I've been trying to import the explorer in my npm (webpack) project. I've install `keen-explorer` through `yarn` and when doing an `import KeenExplorer from 'keen-explorer'`, all I got is an "Unable to resolve path to module 'keen-explorer'"

When I go check the `package.json` of `keen-explorer` inside of my `node_modules`, I can see that there are actually no `main` key, no any `index.js` file in the root.

How can I import the explorer without resorting to fetching it from the front-end in its own `script` tag? Am I doing something wrong?

Thanks for your answers,

**Comment by pixelastic** [comment]
I worked around my issue by doing an 

```javascript
import KeenExplorer from 'keen-explorer/dist/keen-explorer.js';
```

And then accessing it through window.Keen.Explorer, but that still require access to the global element (and needs jQuery available in the global namespace as well).

**Comment by adamkasprowicz** [comment]
This issue is fixed in the most recent version of the package - keen-explorer@4.0.1
