### ISSUE TITLE
Explorer legends in Hebrew are reversed

### ISSUE THREAD

**Issue by tautau** [keen/explorer#230]
In Dashboard/Explorer, values that are Hebrew strings, are reversed. Probably because it's an RTL language.

**Comment by adamkasprowicz** [comment]
I guess this could be solved with CSS property `direction: rtl;`. I can't debug it further without more informations, please let me know if this issue still occurs.

**Comment by tautau** [comment]
Labels in Hebrew are no longer reversed. This issue seems to have been fixed/resolved at some point in time between April and July. So thank you!
