### ISSUE TITLE
Contrast in not good in the UI

### ISSUE THREAD

**Issue by stof** [keen/explorer#238]
For instance, with a filter selected, the UI looks like that: 
![explorer_contrast](https://user-images.githubusercontent.com/439401/44660143-0af32500-aa07-11e8-8496-a742a5615981.png)

These colors have a contrast of 1.11: https://contrast-ratio.com/#white-on-%23f2f2f2. At a 16px font size, for non-bold text, the minimum contrast for the AA accessibility level is 4.5.

**Comment by adamkasprowicz** [comment]
Thank you for reporting, you're totally right. I'm adding this to our backlog.
