### ISSUE TITLE
Using Arrayed Query Results as Filters in Related Queries

### ISSUE THREAD

**Issue by mrtannerjones** [keen/explorer#27]
Thing that would be awesome: If you could create explorer queries using the results of other queries as filters.  
 
Something that would look like this:

http://content.screencast.com/users/tannerjjones/folders/Jing/media/30678b98-f954-4c75-89c8-d4b8ffa1a129/00000138.png

**Comment by dustinlarimer** [comment]
@mrtannerjones that's a pretty awesome idea! We have a pretty aggressive roadmap right now, so I'm afraid this isn't something we'll be tackling in the near future, but I'll keep a note of this for future feature considerations. Thanks for sharing!
