### ISSUE TITLE
Allow filters to equate to an empty string.

### ISSUE THREAD

**Issue by hex337** [keen/explorer#29]
Right now, you can't create a filter to check for the equalness or non-equalness of an empty string (it just removes the filter). There are cases where you would want to check for an empty string or when that field is not empty.

**Comment by dustinlarimer** [comment]
:+1: we'll look into this, thanks!

**Comment by SteeleParker** [comment]
Just a little further info:

Currently the API allows the checking of `equal to` or `not equal to` an empty string, however the explorer gives an error when attempting to save a filter with either of these constraints

For Example, the following is an accepted filter through the API
`{property_name: "myProperty", operator: "ne", property_value: ""}`
