### ISSUE TITLE
Save Query Tab

### ISSUE THREAD

**Issue by maciejrybaniec** [keen/explorer#304]
The _SaveQuery_ component is not displayed correctly according to Explorer configuration flags.

**Steps to reproduce**

1. Navigate to Keen.io and login as user
2. Navigate to Explorer v6 section.
3. Create and save a query

**Result**
The Browse tab is not displayed

**Expected**
The query should be saved and visible in Browse tab

**Comment by stof** [comment]
I see a merged PR referencing this issue, but I'm still not seeing the Browse tab on keen.io (while I do have existing saved queries)

**Comment by maciejrybaniec** [comment]
Hi @stof. The fix for the issue should be deployed on production at the beginning of this week.

**Comment by maciejrybaniec** [comment]
@stof the Browse tab for Explorer v6 should be visible on keen.io.

**Comment by stof** [comment]
@maciejrybaniec it is still not displayed for me

**Comment by stof** [comment]
OK, looks like the deployment was not done yet at that time.
