### ISSUE TITLE
Saving queries is broken

### ISSUE THREAD

**Issue by stof** [keen/explorer#318]
For testing purposes (to see whether saving a new query would make the browse tab appear), I tried saving the most basic query: a count query on this 14 days on my collection, with no grouping and no filtering.
Saving this query failed with the following response from the API: 

```json
{"message": "The specified property is invalid for this cached query. Property: 'percentile'.", "error_code": "InvalidPropertyForCachedQuery"}
```

**Comment by apryka** [comment]
@stof can you please re-test? We've deployed a new version on prod today and this should not be an issue now

**Comment by stof** [comment]
When was the deployment ? I got the issue exactly at the time I opened the github issue.

**Comment by stof** [comment]
OK, the deployment was after my test. This is indeed fixed now.
