### ISSUE TITLE
Remove internet connection requirement for running tests

### ISSUE THREAD

**Issue by aroc** [keen/explorer#47]
Tests make use of CDN hosted versions of jQuery and Keen.js. Ideally, you shouldn't need an internet connection to run tests.

**Comment by josephwegner** [comment]
Do we just want to keep a local version of these in test/support?

**Comment by aroc** [comment]
I believe that's the best way to handle it.

**Comment by josephwegner** [comment]
I'm actually loading them in via NPM... That seems more future proof, I think.

**Comment by aroc** [comment]
Agreed!
