### ISSUE TITLE
npm install fails on mocha-phantomjs

### ISSUE THREAD

**Issue by xpollen8** [keen/explorer#5]
```
npm ERR! peerinvalid The package phantomjs does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer mocha-phantomjs@3.6.0 wants phantomjs@1.9.1 - 1.9.7-15

npm ERR! System Linux 3.13.0-58-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/ubuntu/dash
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code EPEERINVALID
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ubuntu/dash/npm-debug.log
npm ERR! not ok code 0
```

**Comment by dustinlarimer** [comment]
@xpollen8 this has been happening on a few of our JS repos.. try wiping out `node_modules`, updating `package.json` with these diffs, and re-installing: https://github.com/keen/keen-js/commit/5d126f9dfa42a3b1421917f49d39e775a9eb8039

**Comment by xpollen8** [comment]
The above diff is significantly different from the HEAD version of packages.json. just applying these additions fo HEAD doesn't significantly improve the situation..

If I start with the full packages.json shown in the diff, then gulp complains of about a dozen missing gulp-X dependencies. After adding those dependencies then has 'gulp' finally choking inside client/js/app/app.js with:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Parsing file /home/ubuntu/dash/client/js/app/app.js: Unexpected token (63:4)

**Comment by dustinlarimer** [comment]
@xpollen8 sorry for the confusing comment – that diff is from a different project, but the common dependencies for this project just need to be updated similarly to resolve the `peerinvalid` error. Try explicitly setting and installing **phantomjs** @ 1.9.17. I believe that should do the trick, but please let me know if that's not the case!

**Comment by xpollen8** [comment]
no go. a clean install with phantomjs @ 1.9.17 yields:

﻿﻿﻿﻿﻿
<img width="818" alt="untitled" src="https://cloud.githubusercontent.com/assets/552254/8971918/f877f2da-3609-11e5-827f-c562f57034da.png">

**Comment by dustinlarimer** [comment]
@xpollen8 try wiping your node_modules directory again and updating these dependency versions:

```json
  "gulp-mocha-phantomjs": "0.8.1",
  "mocha-phantomjs": "^3.6.0",
  "phantomjs": "1.9.7-15"
```

**Comment by xpollen8** [comment]
closer.  now into app errors (sorry to be being such a pain!)

<img width="869" alt="untitled" src="https://cloud.githubusercontent.com/assets/552254/8972460/46dc3832-360f-11e5-9642-2920f9c1d224.png">


﻿

**Comment by dustinlarimer** [comment]
No worries – however, that appears to be a different issue :)

That file is named REST.js, but I'm wondering why this error doesn't occur on my machine. Try renaming the file (lowercase) and let me know if this resolves the issue.

**Comment by xpollen8** [comment]
ta-da. that did it
