### ISSUE TITLE
queries do not run when clicked on http://keen.github.io/explorer

### ISSUE THREAD

**Issue by lexicography** [keen/explorer#55]
The queries do not automatically run when they're clicked. 

http://keen.github.io/explorer/?query%5Bevent_collection%5D=page_load&query%5Banalysis_type%5D=count&query%5Btimezone%5D=UTC&query%5Btimeframe%5D=this_1_weeks&visualization%5Bchart_type%5D=metric#demo

**Comment by josephwegner** [comment]
This just needs the latest version of Explore moved over to gh-pages... @dustinlarimer I keep forgetting - is there some magic that needs to happen to explorer before it gets moved to that page? Or just a straight copy?

**Comment by dustinlarimer** [comment]
@josephwegner it's a straight copy right now, just remember to run the actual build task(s) first so you don't pull a #sweetmove like me and copy an outdated version over :grin:

**Comment by dustinlarimer** [comment]
Seems to be resolved :+1:
