### ISSUE TITLE
Feature request - batched extracts

### ISSUE THREAD

**Issue by wheresrhys** [keen/explorer#58]
Not sure which repo to raise this in, so raising it here.

I need to extract all events of a certain type for the last 6 months. Doing this as a single extraction fails as I guess keen can't handle it, so I have selected some date ranges and eventually successfully extracted all the data I need like that.

However this is also far from ideal. It's meant a lot of trial and error and tedious form manipulation in order to find date ranges that are small enough to be exported. Once exported I also have the problem that some of the exports are so large that they cannot be converted into json as they exceed the memory and/or language limitations of javascript and my laptop.

What I really need is a proper batched extract - I send a request for a certain collection of data, but am able to stipulate the maximum size of a single extract, and keen batches up the data into files no bigger than these limits (specified in MB or row count) and sends them to me.

Is this a feature you'd be open to developing?

**Comment by wheresrhys** [comment]
Or for the synchronous api, it could accept an additional header/parameter `batched: true`, and this results in a series of responses using `Link` headers http://www.w3.org/wiki/LinkHeader

**Comment by dustinlarimer** [comment]
@wheresrhys thanks for the suggestion– and my apologies for the super long delay in replying here. I'm afraid this isn't something we'll pursue for extractions, although I suspect forwarding your event stream to S3 may be a workable technique to get large batches of event data into another format.

**Comment by dustinlarimer** [comment]
If you would like to chat more about S3 streaming, feel free to give us a shout at [team@keen.io](mailto:team@keen.io)!
