### ISSUE TITLE
Filters on saved queries with property_value strings can be interpreted as dates

### ISSUE THREAD

**Issue by dustinlarimer** [keen/explorer#59]
If a filter's `property_value` can be parsed into a valid `Date` object, that filter value will get handled as such. Eg: "2015" becomes "2015-11-19T00:00:00". This occurs prior to saving a given query, meaning the saved query parameters are also incorrect.
1. Create a filter for a property where `operator` equals a string value of 2015
2. Close filter modal
3. Name and save the query
4. Reload the query and re-open the filter modal
5. That filter's property value is now "2015-11-19T00:00:00".

<img width="432" alt="screen shot 2015-11-19 at 12 55 23 pm" src="https://cloud.githubusercontent.com/assets/180438/11284090/d561f53c-8ebc-11e5-85bd-b42efd5b0e57.png">

<img width="436" alt="screen shot 2015-11-19 at 12 55 15 pm" src="https://cloud.githubusercontent.com/assets/180438/11284096/ddf5c30e-8ebc-11e5-943a-1bf614478109.png">

**Comment by aroc** [comment]
As part of this fix, we should make the change to only allow `Datetime` coercion type on `keen.timestamp` and `keen.created_at`, as datetime's only work on those properties anyway.
