### ISSUE TITLE
Boolean filter values handled as strings

### ISSUE THREAD

**Issue by dustinlarimer** [keen/explorer#65]
Filter values of `true|false` fail internal validation, resulting in an error message of:

> The specified value is invalid for the given operator. Operator: exists. Value: false

**Comment by wetzler** [comment]
The filter works the first time you place it, but fails when you copy & paste an explorer URL. 

Steps to reproduce:

1. Create a query like "count" pageviews today
2. Add a filter like "url.relative exists false"
3. Run the query (it should work)
4. Copy the explorer URL and paste it into a new browser session -> get the error "The specified value is invalid for the given operator. Operator: exists. Value: false"
