### ISSUE TITLE
Timeframe text description does not pluralize to match dropdown 

### ISSUE THREAD

**Issue by tedmiston** [keen/explorer#7]
When running a query with a timeframe, you can change the unit amongst minutes/hours/days/etc.  You can also change the number of units.  When I change the number of units to be > 1, the description updates.

Actual: The last 3 day including the current day.
Expected: The last 3 day**s** including the current day.

<img width="496" alt="screen shot 2015-07-29 at 5 28 57 pm" src="https://cloud.githubusercontent.com/assets/366688/8970369/55b7ea74-3617-11e5-9f3c-59dfa89e57ca.png">

Note: I took this screenshot on the production version running on keen.io.

*(I recognize this is an exceedingly tiny issue, but still wanted to document it for completeness.)*

**Comment by dustinlarimer** [comment]
Thanks for this @tedmiston!
