### ISSUE TITLE
Explorer ought to display the timezone of a time displayed in charts or tables

### ISSUE THREAD

**Issue by eliot-keen** [keen/explorer#74]
Explorer displays dates without timezone information in chart and table views so when you mouse over a point in a chart you get something like "Nov 30, 2015 4:00PM" with no information about what timezone that is being used to interpret that date and time. It would be quite helpful if the date and time was displayed with the current timezone in use in the chart or table, e.g. "Nov 30, 2015 4:00PM (PST)" for Pacific Standard Time.

**Comment by adamkasprowicz** [comment]
Currently, explorer is displaying Timezone in the panel, with ability to change it.
