### ISSUE TITLE
Saving a query breaks explorer: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by wetzler** [keen/explorer#77]
I tried to create a simple query for testing purposes. Saving it seems to break the explorer.

Steps to repro:
1. Go to the project.
2. Select a count for the collection "data"
3. Enter timeframe "this 14 years"
4. Run Query.
5. Enter title "Simple Query 2"
6. Click Save query.

Result => Error in console: "cannot read property 'length' of null". 
The explorer sort of breaks and I can't even create new queries. 

I will send you the link to try it out  yourself.

**Comment by aroc** [comment]
Fixed by #79
