### ISSUE TITLE
 “group_by” param in the API Query URL does not group

### ISSUE THREAD

**Issue by wetzler** [keen/explorer#81]
There is an issue w/ the “group_by” param in the API Query URL that you generate in the Explorer that, in effect, *does not* group the query results :

api.keen.io/3.0/projects/project/queries/count?api_key=key&timezone=US%2FEastern&timeframe=this_30_days&**group_by%5B0%5D=app.name**&event_collection=Viewed%20photo&filters=%5B%5D

I bolded the text — but here is what it does: &group_by%5B0%5D=

Realized this an hour into futzing with it and trying to figure out why I couldn’t import the JSON into a Google Doc. Removing that invalid character fixed it immediately.

Am giving you a heads up, since I assume this is a widespread issue and not unique to our account.

**Comment by aroc** [comment]
PR ready for review: #84
