### ISSUE TITLE
Analyses with only 1 group-by field return results with an "undefined" label attached to each group

### ISSUE THREAD

**Issue by maggiejan** [keen/explorer#82]
For all analyses which only have 1 group-by field, the returned result now shows up with the label "undefined" after every field value. 

By adding a 2nd group-by, the "undefined" field is replaced by the property category of the 2nd group-by. 

Error reported through Keen Support Pool & the error is reproducible. 
![screen shot 2015-12-21 at 3 31 08 pm](https://cloud.githubusercontent.com/assets/8227394/11944081/e48c4c02-a7f7-11e5-9e9c-a5e93ec71f8b.png)

**Comment by aroc** [comment]
@maggiejan I'm having a hard time reproducing this one - can you give me specific steps.

**Comment by maggiejan** [comment]
Yeah! Sure!

Here's a link to the type of query parameters that are used in an actual
query, I can provide more if needed.
https://keen.io/project/53cd895d2481967fba000002/explorer?query%5Bevent_collection%5D=purchases&query%5Banalysis_type%5D=count&query%5Bgroup_by%5D%5B0%5D=user.first_name&query%5Btimezone%5D=UTC&query%5Btimeframe%5D=previous_14_months

Instructions:
1) select an event collection
2) select "count" (any analysis also produces this label glitch)
3) choose "group by", select one field to group by
4) leave the second "group by" alone (do not input a second field to group
by)
5) use a valid timeframe
6) hit "run"

On Monday, December 21, 2015, Eric Anderson <notifications@github.com>
wrote:

> @maggiejan <https://github.com/maggiejan> I'm having a hard time
> reproducing this one - can you give me specific steps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keen/explorer/issues/82#issuecomment-166507870>.
>


-- 
Data Scientist | Keen IO
@jandwiches  | maggie@keen.io

Join our community Slack chat <http://slack.keen.io/> and try Keen IO
yourself <https://keen.io/signup>!

**Comment by maggiejan** [comment]
Original report via Keen user:
https://app.intercom.io/a/apps/5eadb8aff7474e2d465c4fc13242935d5b4e1405/inbox/maggie@keen.io/conversations/1587448164
(login required)

On Mon, Dec 21, 2015 at 9:59 PM, Maggie Jan <maggie@keen.io> wrote:

> Yeah! Sure!
>
> Here's a link to the type of query parameters that are used in an actual
> query, I can provide more if needed.
> https://keen.io/project/53cd895d2481967fba000002/explorer?query%5Bevent_collection%5D=purchases&query%5Banalysis_type%5D=count&query%5Bgroup_by%5D%5B0%5D=user.first_name&query%5Btimezone%5D=UTC&query%5Btimeframe%5D=previous_14_months
>
> Instructions:
> 1) select an event collection
> 2) select "count" (any analysis also produces this label glitch)
> 3) choose "group by", select one field to group by
> 4) leave the second "group by" alone (do not input a second field to group
> by)
> 5) use a valid timeframe
> 6) hit "run"
>
> On Monday, December 21, 2015, Eric Anderson <notifications@github.com>
> wrote:
>
>> @maggiejan <https://github.com/maggiejan> I'm having a hard time
>> reproducing this one - can you give me specific steps.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/keen/explorer/issues/82#issuecomment-166507870>.
>>
>
>
> --
> Data Scientist | Keen IO
> @jandwiches  | maggie@keen.io
>
> Join our community Slack chat <http://slack.keen.io/> and try Keen IO
> yourself <https://keen.io/signup>!
>
>


-- 
Data Scientist | Keen IO
@jandwiches  | maggie@keen.io

Join our community Slack chat <http://slack.keen.io/> and try Keen IO
yourself <https://keen.io/signup>!

**Comment by aroc** [comment]
@dustinlarimer Any thoughts on this? I tried it out with Keen.js (`3.4.0-rc2`) and a single item array for a group_by does cause this. I think it's from this line in keen.js: https://github.com/keen/keen-js/blob/master/src/dataviz/helpers/getQueryDataType.js#L4

**Comment by aroc** [comment]
Fixed in `keen.js 3.4.0-rc2`.

**Comment by dustinlarimer** [comment]
_Updated comment to `keen.js 3.4.0-rc3`_
