### ISSUE TITLE
Link to demo in README.md points to http://localhost:8081/explorer

### ISSUE THREAD

**Issue by dantreasure** [keen/explorer#9]
I'm guessing there is a hosted instance of this somewhere you intended to point to. If not no big deal.

**Comment by aroc** [comment]
This line just needs to be clarified: We intended to get you set up locally then go visit the *localhost* demo. Thanks for pointing this out!!!

**Comment by aroc** [comment]
Fixed by https://github.com/keen/explorer/pull/10

**Comment by dantreasure** [comment]
That makes more sense. Thanks for having such a well done README.md!

**Comment by aroc** [comment]
No problem! Thanks for helping make it better! :)
