### ISSUE TITLE
Feature request: export to CSV from Table view

### ISSUE THREAD

**Issue by nemo** [keen/explorer#94]
Hey folks,

I think it's an obvious extension to the table view of the data to have an `Download as CSV` button of some sort.

This will make it easy to do further analysis in Excel/Spreadsheets outside of Keen (for example, when you want to perform rate of change and/or accumulation).

**Comment by wetzler** [comment]
Hey! Great feature request. In the meantime, I wanted to let you know about this google spreadheets hack that always you to get your data into tables relatively quickly:
https://www.linkedin.com/pulse/simplest-way-import-your-keen-io-data-google-sheets-gabellieri

**Comment by wetzler** [comment]
One more thing, it's a little bit awkward to copy & paste tables out of Keen, but it is possible. Try starting from the bottom right corner and scrolling up (but not too far) to select the table contents and then copy & page into excel.

**Comment by nemo** [comment]
Thanks @wetzler – ended up figuring out how to copy it from the table. Still would be great to have the button :P

**Comment by dustinlarimer** [comment]
@nemo @wetzler this is now in production- thanks for the nudge! Enjoy!
