### ISSUE TITLE
Update hosted assets for multiple group-by support

### ISSUE THREAD

**Issue by garethtdavies** [keen/explorer#99]
Currently the linked assets here https://github.com/keen/explorer#option-1-use-the-hosted-assets-from-our-cdn point to an old version of keen.js and keen-explorer.js. Can these be updated?

**Comment by aroc** [comment]
@garethtdavies Yes they can! In fact, I'm going to cut a new release of Explorer as there have been several critical bugfixes, performance improvements, etc. Thanks for pointing this out. I'll close this issue once a new release is ready.

**Comment by aroc** [comment]
Explorer `2.1.0` is out and on the CDN. :D Enjoy!

https://github.com/keen/explorer/releases/tag/v2.1.0

**Comment by aroc** [comment]
@garethtdavies I just pushed up `2.2.0` as well, as it contains the ability to save funnel queries. You might want to use that one instead. :)

**Comment by garethtdavies** [comment]
Awesome thanks! Working great and saved funnel queries are a great extra bonus :+1:
